const fragmenter = require('@flybywiresim/fragmenter');
const fs = require('fs');

const execute = async () => {
    try {
        const result = await fragmenter.pack({
            packOptions: { splitFileSize: 102_760_448, keepCompleteModulesAfterSplit: false },
            baseDir: './build-a320ceo/out/lvfr-horizonsim-airbus-a320-ceo',
            outDir: './build-a320ceo/out/build-modules',
            modules: [{
                name: 'effects',
                sourceDir: './effects'
            }, {
                name: 'html_ui',
                sourceDir: './html_ui'
            }, {
                name: 'ModelBehaviorDefs',
                sourceDir: './ModelBehaviorDefs'
            }, {
                name: 'A320ceoCFM_Model',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/model'
            }, {
                name: 'A320ceoCFM_Model_SAT',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/model.SAT'
            }, {
                name: 'A320ceoCFM_Panel',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/panel'
            }, {
                name: 'A320ceoCFM_Sound',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/sound'
            }, {
                name: 'A320ceoCFM_Texture',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/TEXTURE'
            }, {
                name: 'A320ceoCFM_Texture_AAL',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AAL'
            }, {
                name: 'A320ceoCFM_Texture_AAY',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AAY'
            }, {
                name: 'A320ceoCFM_Texture_ACA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.ACA'
            }, {
                name: 'A320ceoCFM_Texture_ACA2',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.ACA2'
            }, {
                name: 'A320ceoCFM_Texture_AFL',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AFL'
            }, {
                name: 'A320ceoCFM_Texture_AFR',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AFR'
            }, {
                name: 'A320ceoCFM_Texture_AMC',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AMC'
            }, {
                name: 'A320ceoCFM_Texture_ANA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.ANA'
            }, {
                name: 'A320ceoCFM_Texture_APJ',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.APJ'
            }, {
                name: 'A320ceoCFM_Texture_ASA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.ASA'
            }, {
                name: 'A320ceoCFM_Texture_AUA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AUA'
            }, {
                name: 'A320ceoCFM_Texture_AVA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AVA'
            }, {
                name: 'A320ceoCFM_Texture_AWE',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AWE'
            }, {
                name: 'A320ceoCFM_Texture_AXM',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AXM'
            }, {
                name: 'A320ceoCFM_Texture_AZA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.AZA'
            }, {
                name: 'A320ceoCFM_Texture_BEL',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.BEL'
            }, {
                name: 'A320ceoCFM_Texture_CCA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CCA'
            }, {
                name: 'A320ceoCFM_Texture_CES',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CES'
            }, {
                name: 'A320ceoCFM_Texture_CFG',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CFG'
            }, {
                name: 'A320ceoCFM_Texture_CFG2',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CFG2'
            }, {
                name: 'A320ceoCFM_Texture_CQH',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CQH'
            }, {
                name: 'A320ceoCFM_Texture_CRK',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CRK'
            }, {
                name: 'A320ceoCFM_Texture_CSN',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.CSN'
            }, {
                name: 'A320ceoCFM_Texture_DAL',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.DAL'
            }, {
                name: 'A320ceoCFM_Texture_DLH',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.DLH'
            }, {
                name: 'A320ceoCFM_Texture_DLH2',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.DLH2'
            }, {
                name: 'A320ceoCFM_Texture_DLH3',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.DLH3'
            }, {
                name: 'A320ceoCFM_Texture_EDW',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EDW'
            }, {
                name: 'A320ceoCFM_Texture_EIN',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EIN'
            }, {
                name: 'A320ceoCFM_Texture_EIN2',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EIN2'
            }, {
                name: 'A320ceoCFM_Texture_EWG',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EWG'
            }, {
                name: 'A320ceoCFM_Texture_EZY',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EZY'
            }, {
                name: 'A320ceoCFM_Texture_EZY2',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EZY2'
            }, {
                name: 'A320ceoCFM_Texture_EZY3',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.EZY3'
            }, {
                name: 'A320ceoCFM_Texture_FIN',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.FIN'
            }, {
                name: 'A320ceoCFM_Texture_GWI',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.GWI'
            }, {
                name: 'A320ceoCFM_Texture_GXA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.GXA'
            }, {
                name: 'A320ceoCFM_Texture_IBE',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.IBE'
            }, {
                name: 'A320ceoCFM_Texture_IBS',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.IBS'
            }, {
                name: 'A320ceoCFM_Texture_IRA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.IRA'
            }, {
                name: 'A320ceoCFM_Texture_ITY',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.ITY'
            }, {
                name: 'A320ceoCFM_Texture_LAN',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.LAN'
            }, {
                name: 'A320ceoCFM_Texture_MEA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.MEA'
            }, {
                name: 'A320ceoCFM_Texture_PIA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.PIA'
            }, {
                name: 'A320ceoCFM_Texture_ROU',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.ROU'
            }, {
                name: 'A320ceoCFM_Texture_SDR',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.SDR'
            }, {
                name: 'A320ceoCFM_Texture_SWR',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.SWR'
            }, {
                name: 'A320ceoCFM_Texture_TAP',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.TAP'
            }, {
                name: 'A320ceoCFM_Texture_TAR',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.TAR'
            }, {
                name: 'A320ceoCFM_Texture_VLG',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.VLG'
            }, {
                name: 'A320ceoCFM_Texture_VOE',
                sourceDir: './SimObjects/Airplanes/A320ceoCFM/texture.VOE'
            }, {
                name: 'A320ceoCFMsl_Model',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/model'
            }, {
                name: 'A320ceoCFMsl_Model_SAT',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/model.SAT'
            }, {
                name: 'A320ceoCFMsl_Panel',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/panel'
            }, {
                name: 'A320ceoCFMsl_Sound',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/sound'
            }, {
                name: 'A320ceoCFMsl_Texture',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/TEXTURE'
            }, {
                name: 'A320ceoCFMsl_Texture_DLH',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/texture.DLH'
            }, {
                name: 'A320ceoCFMsl_Texture_DLH2',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/texture.DLH2'
            }, {
                name: 'A320ceoCFMsl_Texture_EWG',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/texture.EWG'
            }, {
                name: 'A320ceoCFMsl_Texture_EZY',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/texture.EZY'
            }, {
                name: 'A320ceoCFMsl_Texture_FFT',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/texture.FFT'
            }, {
                name: 'A320ceoCFMsl_Texture_SVA',
                sourceDir: './SimObjects/Airplanes/A320ceoCFMsl/texture.SVA'
            }, {
                name: 'A320ceoIAE_Model',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/model'
            }, {
                name: 'A320ceoIAE_Model_SAT',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/model.SAT'
            }, {
                name: 'A320ceoIAE_Panel',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/panel'
            }, {
                name: 'A320ceoIAE_Sound',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/sound'
            }, {
                name: 'A320ceoIAE_Texture',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/TEXTURE'
            }, {
                name: 'A320ceoIAE_Texture_AAL',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.AAL'
            }, {
                name: 'A320ceoIAE_Texture_AEE',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.AEE'
            }, {
                name: 'A320ceoIAE_Texture_ANZ',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.ANZ'
            }, {
                name: 'A320ceoIAE_Texture_AWC',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.AWC'
            }, {
                name: 'A320ceoIAE_Texture_AWC2',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.AWC2'
            }, {
                name: 'A320ceoIAE_Texture_BAW',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.BAW'
            }, {
                name: 'A320ceoIAE_Texture_ISR',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.ISR'
            }, {
                name: 'A320ceoIAE_Texture_JBU',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.JBU'
            }, {
                name: 'A320ceoIAE_Texture_JBU2',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.JBU2'
            }, {
                name: 'A320ceoIAE_Texture_JBU3',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.JBU3'
            }, {
                name: 'A320ceoIAE_Texture_JST',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.JST'
            }, {
                name: 'A320ceoIAE_Texture_LDA',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.LDA'
            }, {
                name: 'A320ceoIAE_Texture_NKS',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.NKS'
            }, {
                name: 'A320ceoIAE_Texture_NWK',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.NWK'
            }, {
                name: 'A320ceoIAE_Texture_QTR',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.QTR'
            }, {
                name: 'A320ceoIAE_Texture_SAA',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.SAA'
            }, {
                name: 'A320ceoIAE_Texture_SAS',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.SAS'
            }, {
                name: 'A320ceoIAE_Texture_TAM',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.TAM'
            }, {
                name: 'A320ceoIAE_Texture_TGW',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.TGW'
            }, {
                name: 'A320ceoIAE_Texture_THY',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.THY'
            }, {
                name: 'A320ceoIAE_Texture_UAL',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.UAL'
            }, {
                name: 'A320ceoIAE_Texture_UAL2',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.UAL2'
            }, {
                name: 'A320ceoIAE_Texture_UAL3',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.UAL3'
            }, {
                name: 'A320ceoIAE_Texture_VOI',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.VOI'
            }, {
                name: 'A320ceoIAE_Texture_WZZ',
                sourceDir: './SimObjects/Airplanes/A320ceoIAE/texture.WZZ'
            }, {
                name: 'A320ceoIAEsl_Model',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/model'
            }, {
                name: 'A320ceoIAEsl_Model_SAT',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/model.SAT'
            }, {
                name: 'A320ceoIAEsl_Panel',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/panel'
            }, {
                name: 'A320ceoIAEsl_Sound',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/sound'
            }, {
                name: 'A320ceoIAEsl_Texture',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/TEXTURE'
            }, {
                name: 'A320ceoIAEsl_Texture_BAW',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.BAW'
            }, {
                name: 'A320ceoIAEsl_Texture_ETD',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.ETD'
            }, {
                name: 'A320ceoIAEsl_Texture_IGO',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.IGO'
            }, {
                name: 'A320ceoIAEsl_Texture_JBU',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.JBU'
            }, {
                name: 'A320ceoIAEsl_Texture_NKS',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.NKS'
            }, {
                name: 'A320ceoIAEsl_Texture_NKS2',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.NKS2'
            }, {
                name: 'A320ceoIAEsl_Texture_VIV',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.VIV'
            }, {
                name: 'A320ceoIAEsl_Texture_VLG',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.VLG'
            }, {
                name: 'A320ceoIAEsl_Texture_WZZ',
                sourceDir: './SimObjects/Airplanes/A320ceoIAEsl/texture.WZZ'
            }]
        });
        console.log(result);
        console.log(fs.readFileSync('./build-a320ceo/out/build-modules/modules.json').toString());
    } catch (e) {
        console.error(e);
        process.exit(1);
    }
};

execute();