const fragmenter = require('@flybywiresim/fragmenter');
const fs = require('fs');

const execute = async () => {
    try {
        const result = await fragmenter.pack({
            packOptions: { splitFileSize: 102_760_448, keepCompleteModulesAfterSplit: false },
            baseDir: './build-a319ceo/out/lvfr-horizonsim-airbus-a319-ceo',
            outDir: './build-a319ceo/out/build-modules',
            modules: [{
                name: 'effects',
                sourceDir: './effects'
            }, {
                name: 'html_ui',
                sourceDir: './html_ui'
            }, {
                name: 'ModelBehaviorDefs',
                sourceDir: './ModelBehaviorDefs'
            }, {
                name: 'A319ceoCFM_Model',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/model'
            }, {
                name: 'A319ceoCFM_Model_EZY',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/model.EZY'
            }, {
                name: 'A319ceoCFM_Panel',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/panel'
            }, {
                name: 'A319ceoCFM_Sound',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/sound'
            }, {
                name: 'A319ceoCFM_Texture',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture'
            }, {
                name: 'A319ceoCFM_Texture_AAL',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AAL'
            }, {
                name: 'A319ceoCFM_Texture_AAL2',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AAL2'
            }, {
                name: 'A319ceoCFM_Texture_AAY',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AAY'
            }, {
                name: 'A319ceoCFM_Texture_ACA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.ACA'
            }, {
                name: 'A319ceoCFM_Texture_ACA2',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.ACA2'
            }, {
                name: 'A319ceoCFM_Texture_AFR',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AFR'
            }, {
                name: 'A319ceoCFM_Texture_AIC',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AIC'
            }, {
                name: 'A319ceoCFM_Texture_AVA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AVA'
            }, {
                name: 'A319ceoCFM_Texture_AZA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.AZA'
            }, {
                name: 'A319ceoCFM_Texture_BEL',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.BEL'
            }, {
                name: 'A319ceoCFM_Texture_CSN',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.CSN'
            }, {
                name: 'A319ceoCFM_Texture_CTN',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.CTN'
            }, {
                name: 'A319ceoCFM_Texture_CYP',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.CYP'
            }, {
                name: 'A319ceoCFM_Texture_DAL',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.DAL'
            }, {
                name: 'A319ceoCFM_Texture_DLH',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.DLH'
            }, {
                name: 'A319ceoCFM_Texture_DLH2',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.DLH2'
            }, {
                name: 'A319ceoCFM_Texture_DLH3',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.DLH3'
            }, {
                name: 'A319ceoCFM_Texture_DRK',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.DRK'
            }, {
                name: 'A319ceoCFM_Texture_EWG',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.EWG'
            }, {
                name: 'A319ceoCFM_Texture_EZY',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.EZY'
            }, {
                name: 'A319ceoCFM_Texture_FIN',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.FIN'
            }, {
                name: 'A319ceoCFM_Texture_GSW',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.GSW'
            }, {
                name: 'A319ceoCFM_Texture_GWI',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.GWI'
            }, {
                name: 'A319ceoCFM_Texture_HFM',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.HFM'
            }, {
                name: 'A319ceoCFM_Texture_IBE',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.IBE'
            }, {
                name: 'A319ceoCFM_Texture_ITY',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.ITY'
            }, {
                name: 'A319ceoCFM_Texture_RJA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.RJA'
            }, {
                name: 'A319ceoCFM_Texture_ROU',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.ROU'
            }, {
                name: 'A319ceoCFM_Texture_SZN',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.SZN'
            }, {
                name: 'A319ceoCFM_Texture_TAM',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.TAM'
            }, {
                name: 'A319ceoCFM_Texture_TAP',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.TAP'
            }, {
                name: 'A319ceoCFM_Texture_TAR',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.TAR'
            }, {
                name: 'A319ceoCFM_Texture_VLG',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.VLG'
            }, {
                name: 'A319ceoCFM_Texture_VOE',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.VOE'
            }, {
                name: 'A319ceoCFM_Texture_VRE',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM/texture.VRE'
            }, {
                name: 'A319ceoCFM_acj_Model',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/model'
            }, {
                name: 'A319ceoCFM_acj_Panel',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/panel'
            }, {
                name: 'A319ceoCFM_acj_Sound',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/sound'
            }, {
                name: 'A319ceoCFM_acj_Texture',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/texture'
            }, {
                name: 'A319ceoCFM_acj_Texture_FRA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/texture.FRA'
            }, {
                name: 'A319ceoCFM_acj_Texture_ITA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/texture.ITA'
            }, {
                name: 'A319ceoCFM_acj_Texture_K5',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/texture.K5'
            }, {
                name: 'A319ceoCFM_acj_Texture_SGS',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/texture.SGS'
            }, {
                name: 'A319ceoCFM_acj_Texture_TBN',
                sourceDir: './SimObjects/Airplanes/A319ceoCFM_acj/texture.TBN'
            }, {
                name: 'A319ceoCFMSL_Model',
                sourceDir: './SimObjects/Airplanes/A319ceoCFMSL/model'
            }, {
                name: 'A319ceoCFMSL_Panel',
                sourceDir: './SimObjects/Airplanes/A319ceoCFMSL/panel'
            }, {
                name: 'A319ceoCFMSL_Sound',
                sourceDir: './SimObjects/Airplanes/A319ceoCFMSL/sound'
            }, {
                name: 'A319ceoCFMSL_Texture',
                sourceDir: './SimObjects/Airplanes/A319ceoCFMSL/texture'
            }, {
                name: 'A319ceoCFMSL_Texture_AAL',
                sourceDir: './SimObjects/Airplanes/A319ceoCFMSL/texture.AAL'
            }, {
                name: 'A319ceoCFMSL_Texture_AVA',
                sourceDir: './SimObjects/Airplanes/A319ceoCFMSL/texture.AVA'
            }, {
                name: 'A319ceoIAE_Model',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/model'
            }, {
                name: 'A319ceoIAE_Model_BAW',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/model.BAW'
            }, {
                name: 'A319ceoIAE_Panel',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/panel'
            }, {
                name: 'A319ceoIAE_Sound',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/sound'
            }, {
                name: 'A319ceoIAE_Texture',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture'
            }, {
                name: 'A319ceoIAE_Texture_AAL',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.AAL'
            }, {
                name: 'A319ceoIAE_Texture_AAL2',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.AAL2'
            }, {
                name: 'A319ceoIAE_Texture_ASL',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.ASL'
            }, {
                name: 'A319ceoIAE_Texture_AVA',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.AVA'
            }, {
                name: 'A319ceoIAE_Texture_BAW',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.BAW'
            }, {
                name: 'A319ceoIAE_Texture_BAW2',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.BAW2'
            }, {
                name: 'A319ceoIAE_Texture_CCA',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.CCA'
            }, {
                name: 'A319ceoIAE_Texture_EWG',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.EWG'
            }, {
                name: 'A319ceoIAE_Texture_NKS',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.NKS'
            }, {
                name: 'A319ceoIAE_Texture_SAA',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.SAA'
            }, {
                name: 'A319ceoIAE_Texture_SAS',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.SAS'
            }, {
                name: 'A319ceoIAE_Texture_THY',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.THY'
            }, {
                name: 'A319ceoIAE_Texture_UAL',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.UAL'
            }, {
                name: 'A319ceoIAE_Texture_UAL2',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.UAL2'
            }, {
                name: 'A319ceoIAE_Texture_VOC',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.VOC'
            }, {
                name: 'A319ceoIAE_Texture_VOI',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE/texture.VOI'
            }, {
                name: 'A319ceoIAE_acj_Model',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE_acj/model'
            }, {
                name: 'A319ceoIAE_acj_Panel',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE_acj/panel'
            }, {
                name: 'A319ceoIAE_acj_Sound',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE_acj/sound'
            }, {
                name: 'A319ceoIAE_acj_Texture',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE_acj/texture'
            }, {
                name: 'A319ceoIAE_acj_Texture_GER',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE_acj/texture.GER'
            }, {
                name: 'A319ceoIAE_acj_Texture_QTR',
                sourceDir: './SimObjects/Airplanes/A319ceoIAE_acj/texture.QTR'
            }]
        });
        console.log(result);
        console.log(fs.readFileSync('./build-a319ceo/out/build-modules/modules.json').toString());
    } catch (e) {
        console.error(e);
        process.exit(1);
    }
};

execute();